apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alpine-nfs
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-deployment
spec:
  selector:
    matchLabels:
      app: alpine
  replicas: 1
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - name: alpine
        image: alpine
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
          - mountPath: /mnt/nfs
            name: data
        command: ["/bin/sh"]
        args: ["-c", "sleep 500000"]
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: alpine-nfs
---
apiVersion: v1
kind: Service
metadata:
  name: alpine
  labels:
    app: alpine
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: alpine
  type: LoadBalancer
