- name: Enable http firewall rule
  firewalld: 
    service: http
    permanent: true
    state: enabled
  notify: restart firewalld

- name: Install nginx
  yum: 
    name: nginx
    state: present

- name: Copy nginx wordpress config file
  template: 
    src: default.conf
    dest: /etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: Start and enable nginx service
  service: 
    name: nginx
    state: started
    enabled: yes

- name: Install php packages
  yum:
    name: php, php-fpm, php-enchant, php-IDNA_Convert, php-mbstring, php-mysql, php-PHPMailer, php-process, php-simplepie, php-xml
    state: present

- name: Disable default pool
  command: mv /etc/php-fpm.d/www.conf /etc/php-fpm.d/www.disabled 
  args:
    creates: /etc/php-fpm.d/www.disabled
  notify: restart php-fpm

- name: Copy php-fpm configuration
  template:
    src: wordpress.conf
    dest: /etc/php-fpm.d/
  notify: restart php-fpm

- name: Create empty wordpress directory
  file:
    path: /srv
    state: directory

- name: Download and extract wordpress archive
  unarchive:
    src: https://en-gb.wordpress.org/wordpress-{{ wp_version }}-en_GB.tar.gz
    dest: /srv
    remote_src: yes
    creates: /srv/wordpress
    
- name: Add group "wordpress"
  group:
    name: wordpress

- name: Add user "wordpress"
  user:
    name: wordpress
    group: wordpress
    home: /srv/wordpress/

# copy wordpress config file
- name: Copy wp-config file
  template:
    src: wp-config.php.j2
    dest: /srv/wordpress/wp-config.php
  notify: restart nginx

- name: Change ownership of wordpress installation
  file:
    path: /srv/wordpress/
    owner: wordpress
    group: wordpress
    state: directory
    recurse: yes
    setype: httpd_sys_content_t

- name: Start php-fpm service
  service:
    name: php-fpm
    state: started
    enabled: yes